### ISSUE TITLE
ADD characters from  Game of thrones series

### ISSUE THREAD

**Issue by patelyash5208** [patelyash5208/GOT---character#1]

**Comment by Tushar7890** [comment]
Assign this to me under hacktoberfest2022 label @patelyash5208

**Comment by Tushar7890** [comment]
> please add 3 or more cahracter @Tushar7890


sure

**Comment by Ns-SheF** [comment]
Hi. This issue is still open right?  Adding characters that is.
(Made some changes but the recent commit was looking entirely different on the page. Had to let go of that)

**Comment by patelyash5208** [comment]
If you know why this happen then solve that problem @Ns-SheF

**Comment by Ns-SheF** [comment]
Fixed that - there were duplicate elements >body,nav,head,char cards.

Will make a pull req after adding some chars.  Thanks

SheF
