### ISSUE TITLE
Add new GOT characters.

### ISSUE THREAD

**Issue by divyanshu-29-7** [patelyash5208/GOT---character#17]
Hey @patelyash5208 i want to add few more characters in the main code so please can i do it?

**Comment by patelyash5208** [comment]
yes sure. @divyanshu-29-7 

please add more character

**Comment by divyanshu-29-7** [comment]
But I wasn't able to create the pull request.
How can i do that could you please direct.
It's for hacktoberfest.

**Comment by patelyash5208** [comment]
You make pull request.
But I don't want any further characters so I close this issue. 
Please star the repo and make pull request @divyanshu-29-7

**Comment by divyanshu-29-7** [comment]
Will do, thanks!
