### ISSUE TITLE
Navbar text (Game Of Thrones) is not horizontally aligned with Home and About

### ISSUE THREAD

**Issue by Anuragsurya318** [patelyash5208/GOT---character#19]
I can fix the alignment of **Game Of Thrones** text in navbar, please kindly assign me this task

**Comment by chharikha2003** [comment]
I have fixed the issue.Can you please check

**Comment by patelyash5208** [comment]
Please provide screenshot of browser output @chharikha2003

**Comment by chharikha2003** [comment]
<img width="944" alt="gameofthrones-1" src="https://user-images.githubusercontent.com/105445283/194737846-40ba78d8-5280-4a12-9881-cf3539517356.png">
<img width="945" alt="gameofthrones-2" src="https://user-images.githubusercontent.com/105445283/194737864-86e75a02-5ad0-4fb8-ac4d-52e72f8ee761.png">

**Comment by chharikha2003** [comment]
Screenshots of both the web pages

**Comment by chharikha2003** [comment]
Can you please check
