### ISSUE TITLE
adding contact us page.

### ISSUE THREAD

**Issue by Pallavibahekar** [patelyash5208/GOT---character#22]
Could you please assign me this iisue under hactoberfest2002?@patelyash5208
.
It will look  like this.
![2022-10-10 (10)](https://user-images.githubusercontent.com/97456579/194808884-a8cb3348-0208-495c-8bad-a2a2a61bdaa3.png)

**Comment by patelyash5208** [comment]
Yes , sure @Pallavibahekar

**Comment by Pallavibahekar** [comment]
thanks sir

**Comment by Pallavibahekar** [comment]
Sir you have not given the tag of hactoberfest-accepted ?

**Comment by patelyash5208** [comment]
I have already given on issues #23
