### ISSUE TITLE
Update Navbar design

### ISSUE THREAD

**Issue by patelyash5208** [patelyash5208/GOT---character#4]

**Comment by darshikaguptaa** [comment]
Sure, can you describe me a little more about the issue

**Comment by Veeno-Rai** [comment]
hey @patelyash5208
kindly assign this issue to me, currently i'm also working in web dev.
I think i can fix this!!

**Comment by patelyash5208** [comment]
@Veeno-Rai please do proper work.
Make design like this , If we click on navbar text then navbar active page display and apply the effect on navbar link text.

**Comment by chharikha2003** [comment]
I would like to work on the issue.Can you please assign it to me

**Comment by patelyash5208** [comment]
<img width="606" alt="image" src="https://user-images.githubusercontent.com/83857159/194708796-618976eb-e0a4-4f4c-88f6-73f971bfe0a2.png">
- Make like this
