### ISSUE TITLE
Code Of Conduct

### ISSUE THREAD

**Issue by myselfdeepdas** [patelyash5208/GOT---character#5]
Hey! I've visited your project and saw, there were no CODE OF CONDUCT for this project.Though code of conduct is necessary for every project for maintaining its open-source contribution decorum. So If you don't mind can i contribute a code of conduct file to this repo ? 😀⚒️

**Comment by myselfdeepdas** [comment]
Please assign me this issue with the label of hacktoberfest-accepted. Thanks ! 😀

**Comment by myselfdeepdas** [comment]
sir you have not added hacktoberfest-accepted tag in your project's About section, please add this because my pr is not counted in hacktoberfest's website

**Comment by patelyash5208** [comment]
I have done that.
Thanks for sharing this information.
